export interface DemoMeta {
  slug: string;
  name: string;
  category: string;
  description: string;
  whatsappNumber: string;
  whatsappLabel: string;
  theme: "dark" | "light" | "warm" | "cool" | "elegant" | "vibrant";
  accentColor: string;
  textColor: string;
  bgColor: string;
}

export const demos: DemoMeta[] = [
  {
    slug: "assistencia-tecnica",
    name: "Resolve Já",
    category: "Assistência Técnica",
    description: "Técnicos, manutenção de celular, notebook, ar-condicionado e serviços de urgência.",
    whatsappNumber: "5511999999001",
    whatsappLabel: "Pedir orçamento no WhatsApp",
    theme: "dark",
    accentColor: "#06b6d4",
    textColor: "#0f172a",
    bgColor: "#0a0a0a",
  },
  {
    slug: "dentista",
    name: "Sorriso Prime",
    category: "Dentista",
    description: "Clínica odontológica com agendamento fácil e atendimento humanizado.",
    whatsappNumber: "5511999999002",
    whatsappLabel: "Agendar avaliação pelo WhatsApp",
    theme: "light",
    accentColor: "#0ea5e9",
    textColor: "#1e293b",
    bgColor: "#f8fafc",
  },
  {
    slug: "advogado",
    name: "Avellar & Costa",
    category: "Advocacia",
    description: "Escritório jurídico com atendimento discreto e consultoria personalizada.",
    whatsappNumber: "5511999999003",
    whatsappLabel: "Falar com advogado pelo WhatsApp",
    theme: "elegant",
    accentColor: "#b45309",
    textColor: "#1c1917",
    bgColor: "#fafaf9",
  },
  {
    slug: "igreja-evento",
    name: "Conferência Avivados 2026",
    category: "Igreja / Evento",
    description: "Eventos, congressos, retiros e inscrições para campanhas especiais.",
    whatsappNumber: "5511999999004",
    whatsappLabel: "Fazer inscrição pelo WhatsApp",
    theme: "vibrant",
    accentColor: "#7c3aed",
    textColor: "#0f172a",
    bgColor: "#0a0a0a",
  },
  {
    slug: "imobiliaria",
    name: "Morar Bem",
    category: "Imobiliária",
    description: "Corretor, imobiliária, lançamentos, aluguel e imóveis selecionados.",
    whatsappNumber: "5511999999005",
    whatsappLabel: "Falar com corretor no WhatsApp",
    theme: "elegant",
    accentColor: "#059669",
    textColor: "#1c1917",
    bgColor: "#fafaf9",
  },
  {
    slug: "automotiva",
    name: "Auto Prime",
    category: "Estética Automotiva",
    description: "Lava-jato, polimento, estética automotiva, martelinho de ouro e insulfilm.",
    whatsappNumber: "5511999999006",
    whatsappLabel: "Pedir orçamento no WhatsApp",
    theme: "dark",
    accentColor: "#ef4444",
    textColor: "#fafafa",
    bgColor: "#171717",
  },
  {
    slug: "cursos",
    name: "Aprender Mais",
    category: "Cursos",
    description: "Reforço escolar, aulas particulares, inglês, informática e cursos livres.",
    whatsappNumber: "5511999999007",
    whatsappLabel: "Falar no WhatsApp",
    theme: "warm",
    accentColor: "#f59e0b",
    textColor: "#1e293b",
    bgColor: "#fff7ed",
  },
  {
    slug: "personalizados",
    name: "Doce Encanto",
    category: "Personalizados / Festas",
    description: "Canecas, azulejos, lembrancinhas, doces, bolos e decoração de festas.",
    whatsappNumber: "5511999999008",
    whatsappLabel: "Pedir orçamento no WhatsApp",
    theme: "warm",
    accentColor: "#ec4899",
    textColor: "#4a044e",
    bgColor: "#fdf2f8",
  },
  {
    slug: "estetica",
    name: "Studio Bella Face",
    category: "Estética",
    description: "Manicure, cílios, sobrancelha, limpeza de pele, depilação e estética facial.",
    whatsappNumber: "5511999999009",
    whatsappLabel: "Agendar pelo WhatsApp",
    theme: "light",
    accentColor: "#d946ef",
    textColor: "#4a044e",
    bgColor: "#fdf4ff",
  },
  {
    slug: "barbearia",
    name: "Barbearia Imperial",
    category: "Barbearia",
    description: "Cortes masculinos, barba, tratamentos e agendamento prático.",
    whatsappNumber: "5511999999010",
    whatsappLabel: "Agendar corte pelo WhatsApp",
    theme: "dark",
    accentColor: "#d97706",
    textColor: "#fafafa",
    bgColor: "#171717",
  },
  {
    slug: "cardapio",
    name: "Sabor Caseiro",
    category: "Cardápio Digital",
    description: "Marmitaria, restaurante, pizzaria, lanchonete e açaí.",
    whatsappNumber: "5511999999011",
    whatsappLabel: "Pedir pelo WhatsApp",
    theme: "warm",
    accentColor: "#dc2626",
    textColor: "#450a0a",
    bgColor: "#fef2f2",
  },
];
